In [3]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
con=sqlite3.connect("im.db")

In [6]:
cur=con.cursor()

In [16]:
cur.execute('''SELECT name FROM sqlite_master WHERE type='table' ''');
cur.fetchall()

[('movie_basics',),
 ('directors',),
 ('known_for',),
 ('movie_akas',),
 ('movie_ratings',),
 ('persons',),
 ('principals',),
 ('writers',)]

In [24]:
q='''SELECT * FROM known_for''';
pd.read_sql_query(q,con)

         person_id   movie_id
0        nm0061671  tt0837562
1        nm0061671  tt2398241
2        nm0061671  tt0844471
3        nm0061671  tt0118553
4        nm0061865  tt0896534
...            ...        ...
1638255  nm9990690  tt9090932
1638256  nm9990690  tt8737130
1638257  nm9991320  tt8734436
1638258  nm9991320  tt9615610
1638259  nm9993380  tt8743182

[1638260 rows x 2 columns]

In [29]:
q='''SELECT * FROM persons''';
pd.read_sql_query(q,con)

,person_id,primary_name,birth_year,death_year,primary_profession
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator"
...,...,...,...,...,...
606643,nm9990381,Susan Grobes,NaN,NaN,actress
606644,nm9990690,Joo Yeon So,NaN,NaN,actress
606645,nm9991320,Madeline Smith,NaN,NaN,actress
606646,nm9991786,Michelle Modigliani,NaN,NaN,producer
606647,nm9993380,Pegasus Envoyé,NaN,NaN,"director,actor,writer"

In [28]:
q='''SELECT * FROM writers''';
pd.read_sql_query(q,con)

         movie_id   person_id
0       tt0285252   nm0899854
1       tt0438973   nm0175726
2       tt0438973   nm1802864
3       tt0462036   nm1940585
4       tt0835418   nm0310087
...           ...         ...
255868  tt8999892  nm10122246
255869  tt8999974  nm10122357
255870  tt9001390   nm6711477
255871  tt9004986   nm4993825
255872  tt9010172   nm8352242

[255873 rows x 2 columns]

In [26]:
q='''SELECT * FROM movie_basics''';
pd.read_sql_query(q,con)

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [27]:
q='''SELECT * FROM principals''';
pd.read_sql_query(q,con)

,movie_id,ordering,person_id,category,job,characters
0,tt0111414,1,nm0246005,actor,None,"[""The Man""]"
1,tt0111414,2,nm0398271,director,None,None
2,tt0111414,3,nm3739909,producer,producer,None
3,tt0323808,10,nm0059247,editor,None,None
4,tt0323808,1,nm3579312,actress,None,"[""Beth Boothby""]"
...,...,...,...,...,...,...
1028181,tt9692684,1,nm0186469,actor,None,"[""Ebenezer Scrooge""]"
1028182,tt9692684,2,nm4929530,self,None,"[""Herself"",""Regan""]"
1028183,tt9692684,3,nm10441594,director,None,None
1028184,tt9692684,4,nm6009913,writer,writer,None
1028185,tt9692684,5,nm10441595,producer,producer,None

In [18]:
cur.execute('''SELECT * FROM movie_akas''');
cur.fetchall()

[('tt0369610', 10, 'Джурасик свят', 'BG', 'bg', None, None, 0.0),
 ('tt0369610', 11, 'Jurashikku warudo', 'JP', None, 'imdbDisplay', None, 0.0),
 ('tt0369610',
  12,
  'Jurassic World: O Mundo dos Dinossauros',
  'BR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610',
  13,
  'O Mundo dos Dinossauros',
  'BR',
  None,
  None,
  'short title',
  0.0),
 ('tt0369610', 14, 'Jurassic World', 'FR', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 15, 'Jurassic World', 'GR', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 16, 'Jurassic World', 'IT', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 17, 'Jurski svijet', 'HR', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 18, "Olam ha'Yura", 'IL', 'he', 'imdbDisplay', None, 0.0),
 ('tt0369610',
  19,
  'Jurassic World: Mundo Jurásico',
  'MX',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610',
  1,
  'Jurassic World: Sauruste maailm',
  'EE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610', 20, 'Jurassic World', 'SE', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 21, 'Jurassic World 3D', 'US', None, None, '3-D version', 0.0),
 ('tt0369610', 22, 'Jurassic World 3D', 'DE', None, None, '3-D version', 0.0),
 ('tt0369610', 23, 'Jurassic World 3D', 'XWW', None, None, '3-D version', 0.0),
 ('tt0369610',
  24,
  'Juras laikmeta pasaule',
  'LV',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610', 25, 'Mundo Jurássico', 'PT', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 26, 'Мир Юрского периода', 'RU', None, None, None, 0.0),
 ('tt0369610', 27, 'Jurský svět', 'CZ', None, None, None, 0.0),
 ('tt0369610', 28, 'Monde jurassique', 'CA', 'fr', 'imdbDisplay', None, 0.0),
 ('tt0369610', 29, 'Jurassic World', 'US', None, None, None, 0.0),
 ('tt0369610', 2, 'Ebb Tide', 'US', None, None, 'fake working title', 0.0),
 ('tt0369610',
  30,
  'Jurassic World: Mundo Jurásico',
  'CL',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610', 31, 'Jurassic World', 'RO', None, 'imdbDisplay', None, 0.0),
 ('tt0369610',
  32,
  'Juros periodo pasaulis',
  'LT',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610', 33, 'Jurassic World', 'FI', None, 'imdbDisplay', None, 0.0),
 ('tt0369610',
  34,
  'Jurassic World: Mundo jurásico',
  'PE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610',
  35,
  'Jurassic Park 4',
  'TR',
  'tr',
  None,
  'informal alternative title',
  0.0),
 ('tt0369610', 36, 'Jurassic Park IV', 'US', None, 'working', None, 0.0),
 ('tt0369610', 37, 'Jurassic World', 'NO', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 38, 'Jurski svet', 'SI', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 39, 'Свiт Юрського перiоду', 'UA', None, None, None, 0.0),
 ('tt0369610', 3, 'The Gioi Khung Long', 'VN', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 40, 'Jurassic World', 'DK', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 41, 'Svet iz doba jure', 'RS', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 42, 'Jurský svet', 'SK', None, None, None, 0.0),
 ('tt0369610', 43, 'Jurassic World', 'TR', 'tr', 'imdbDisplay', None, 0.0),
 ('tt0369610',
  44,
  'Jurassic Park 4',
  'US',
  None,
  None,
  'informal alternative title',
  0.0),
 ('tt0369610', 45, 'Jurassic World', None, None, 'original', None, 1.0),
 ('tt0369610', 46, 'Jurassic World', 'ES', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 47, 'Jurassic World', 'HU', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 48, 'Park jurajski 4', 'PL', None, 'alternative', None, 0.0),
 ('tt0369610', 4, 'Yur dövrü Dünyasi', 'AZ', None, 'imdbDisplay', None, 0.0),
 ('tt0369610',
  5,
  'Iuruli periodis samyaro',
  'GE',
  'ka',
  'imdbDisplay',
  None,
  0.0),
 ('tt0369610', 6, 'Jurassic World', 'PL', None, 'imdbDisplay', None, 0.0),
 ('tt0369610', 7, 'Mundo Jurásico', 'UY', None, None, '3-D version', 0.0),
 ('tt0369610', 8, 'Jurassic World 3D', 'PL', None, None, '3-D version', 0.0),
 ('tt0369610',
  9,
  'Jurassic World - Mundo Jurásico',
  'AR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0381957', 1, 'Cloud Cuckoo Land', 'GB', None, None, None, 0.0),
 ('tt0401729',
  10,
  'Джон Картер: Мiж двох свiтiв',
  'UA',
  None,
  None,
  None,
  0.0),
 ('tt0401729', 11, 'John Carter of Mars', 'US', None, 'working', None, 0.0),
 ('tt0401729', 12, 'A Princess of Mars', 'US', None, 'working', None, 0.0),
 ('tt0401729',
  13,
  'John Carter - Entre dos mundos',
  'AR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0401729',
  14,
  'John Carter Maaveeran',
  'IN',
  'ta',
  None,
  'dubbed version',
  0.0),
 ('tt0401729', 15, 'Džonas Karteris', 'LT', None, None, None, 0.0),
 ('tt0401729', 16, 'John Carter', 'PT', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  17,
  'John Carter: Mezi dvěma světy',
  'CZ',
  None,
  None,
  None,
  0.0),
 ('tt0401729',
  18,
  'John Carter: Ανάμεσα σε δύο κόσμους',
  'GR',
  None,
  None,
  None,
  0.0),
 ('tt0401729',
  19,
  'John Carter: Medzi dvoma svetmi',
  'SK',
  None,
  None,
  None,
  0.0),
 ('tt0401729',
  1,
  'John Carter: Zwischen zwei Welten',
  'DE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0401729', 20, 'Джон Картер', 'RU', None, None, None, 0.0),
 ('tt0401729', 21, 'John Carter', 'FR', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  22,
  'John Carter - Anamesa se dyo kosmous',
  'GR',
  None,
  None,
  'transliterated ISO-LATIN-1 title',
  0.0),
 ('tt0401729',
  23,
  'Джон Картър: Между два свята',
  'BG',
  'bg',
  None,
  None,
  0.0),
 ('tt0401729',
  24,
  'John Carter Mahaveerudu',
  'IN',
  'te',
  None,
  'dubbed version',
  0.0),
 ('tt0401729',
  25,
  'John Carter: Entre dos mundos',
  'PE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0401729', 26, 'John Carter', 'HR', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  27,
  'John Carter: Entre Dois Mundos',
  'BR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt0401729', 28, 'John Carter', 'CL', None, 'imdbDisplay', None, 0.0),
 ('tt0401729', 29, 'John Carter', 'ES', None, 'imdbDisplay', None, 0.0),
 ('tt0401729', 2, 'John Carter', 'US', None, None, None, 0.0),
 ('tt0401729', 30, 'John Carter', 'HU', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  31,
  'John Carter: Iki Dünya Arasinda',
  'TR',
  'tr',
  'imdbDisplay',
  None,
  0.0),
 ('tt0401729', 32, 'John Carter', 'IL', 'he', 'imdbDisplay', None, 0.0),
 ('tt0401729', 33, 'John Carter', 'PL', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  34,
  'John Carter: Entre dos mundos',
  'UY',
  None,
  None,
  '3-D version',
  0.0),
 ('tt0401729', 3, 'John Carter', 'RO', None, 'imdbDisplay', None, 0.0),
 ('tt0401729', 4, 'John Carter', 'CA', 'fr', 'imdbDisplay', None, 0.0),
 ('tt0401729', 5, 'Barsoom', 'US', None, None, 'fake working title', 0.0),
 ('tt0401729',
  6,
  'Džon Karter - Između dva sveta',
  'RS',
  None,
  None,
  None,
  0.0),
 ('tt0401729', 7, 'John Carter', None, None, 'original', None, 1.0),
 ('tt0401729', 8, 'John Carter', 'CO', None, 'imdbDisplay', None, 0.0),
 ('tt0401729',
  9,
  'John Carter: Entre dos mundos',
  'MX',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt10010134',
  1,
  "Versailles Rediscovered - The Sun King's Vanished Palace",
  None,
  None,
  'original',
  None,
  1.0),
 ('tt10010134',
  2,
  'Versailles: Le Palais retrouvé du Roi Soleil',
  'FR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt10010134',
  3,
  'Versailles: Palast des Sonnenkönigs',
  'DE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt10027708',
  1,
  'Miguelito - Canto a Borinquen',
  None,
  None,
  'original',
  None,
  1.0),
 ('tt10027708', 2, 'Miguelito', 'XWW', 'en', 'imdbDisplay', None, 0.0),
 ('tt10027708',
  3,
  'Miguelito - Canto a Borinquen',
  'AU',
  None,
  None,
  None,
  0.0),
 ('tt10027708', 4, 'Miguelito', 'AU', 'en', None, None, 0.0),
 ('tt10050722', 1, "Thing I Don't Get", None, None, 'original', None, 1.0),
 ('tt10050722',
  2,
  'Fünf Dinge, die ich nicht verstehe',
  'DE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt10084780', 1, 'Vinara sodara veera kumara', 'IN', None, None, None, 0.0),
 ('tt10121294',
  1,
  'This Jelly Doughnut Feeling',
  None,
  None,
  'original',
  None,
  1.0),
 ('tt10121294',
  2,
  'This Jelly Doughnut Feeling Ich fühl mich Berliner',
  'DE',
  None,
  None,
  'original script title',
  0.0),
 ('tt1014759',
  10,
  'Alice Dar Sarzamin E Ajayeb',
  'IE',
  'en',
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  11,
  'Η Αλίκη στη χώρα των θαυμάτων',
  'GR',
  None,
  None,
  None,
  0.0),
 ('tt1014759',
  12,
  'Alicia en el país de las maravillas',
  'UY',
  None,
  None,
  None,
  0.0),
 ('tt1014759',
  13,
  'Alice în Tara Minunilor',
  'RO',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  14,
  'Alice no País das Maravilhas',
  'PT',
  None,
  None,
  None,
  0.0),
 ('tt1014759', 15, 'Алиса в Стране чудес', 'RU', None, None, None, 0.0),
 ('tt1014759', 16, "Aliza Be Eretz Ha Pla'ot", 'IL', 'he', None, None, 0.0),
 ('tt1014759', 17, 'Alis harikalar diyarinda', 'TR', 'tr', None, None, 0.0),
 ('tt1014759',
  18,
  'Alice Csodaországban',
  'HU',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 19, 'Alisa stebuklu salyje', 'LT', None, None, None, 0.0),
 ('tt1014759', 1, 'Alice i Underlandet', 'FI', 'sv', 'imdbDisplay', None, 0.0),
 ('tt1014759', 20, 'Alice im Wunderland', 'DE', None, None, None, 0.0),
 ('tt1014759',
  21,
  'Alisa saotsrebata kvekanashi',
  'GE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  22,
  'Alice i Eventyrland',
  'NO',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  23,
  'Alice in Wonderland: An IMAX 3D Experience',
  'US',
  None,
  None,
  'IMAX version',
  0.0),
 ('tt1014759', 24, 'Alice im Wunderland', 'AT', None, None, None, 0.0),
 ('tt1014759',
  25,
  'Alicia en el país de las maravillas',
  'AR',
  None,
  None,
  None,
  0.0),
 ('tt1014759',
  26,
  'Алиса в страната на чудесата',
  'BG',
  'bg',
  None,
  None,
  0.0),
 ('tt1014759',
  27,
  'Alicia en el país de las maravillas',
  'PE',
  None,
  None,
  None,
  0.0),
 ('tt1014759',
  28,
  'Alice i Underlandet',
  'SE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  29,
  'Alicia en el País de las Maravillas',
  'ES',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759',
  2,
  'Alice Csodaországban IMAX 3D',
  'HU',
  None,
  None,
  'IMAX version',
  0.0),
 ('tt1014759',
  30,
  'Alicia en el país de las maravillas',
  'MX',
  None,
  None,
  None,
  0.0),
 ('tt1014759',
  31,
  'I Aliki sti hora ton thavmaton',
  'GR',
  None,
  None,
  'transliterated ISO-LATIN-1 title',
  0.0),
 ('tt1014759',
  32,
  'Alica v cudezni dezeli',
  'SI',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 33, 'Alisa u zemlji čudesa', 'HR', None, None, None, 0.0),
 ('tt1014759', 34, 'Alisa u zemlji čuda', 'RS', None, None, None, 0.0),
 ('tt1014759',
  35,
  'Alice i eventyrland',
  'NO',
  None,
  None,
  'dubbed version',
  0.0),
 ('tt1014759',
  36,
  'Alice au pays des merveilles',
  'CA',
  'fr',
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 37, 'Alice in Wonderland', 'US', None, None, None, 0.0),
 ('tt1014759', 38, 'Liisa Ihmemaassa', 'FI', None, 'imdbDisplay', None, 0.0),
 ('tt1014759',
  39,
  'Alica v krajine zázrakov',
  'SK',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 3, 'Alice in Wonderland', 'JP', 'en', None, None, 0.0),
 ('tt1014759', 40, 'Alice in Wonderland', None, None, 'original', None, 1.0),
 ('tt1014759', 41, 'Alice imedemaal', 'EE', None, None, None, 0.0),
 ('tt1014759',
  42,
  'Alice au pays des merveilles',
  'FR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 4, 'Alice no País das Maravilhas', 'BR', None, None, None, 0.0),
 ('tt1014759', 5, 'Alenka v říši divů', 'CZ', None, None, None, 0.0),
 ('tt1014759', 6, 'Alice', 'US', None, None, 'original script title', 0.0),
 ('tt1014759',
  7,
  'Alicja w Krainie Czarów',
  'PL',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1014759', 8, 'Алiса в краiiнi чудес', 'UA', None, None, None, 0.0),
 ('tt1014759', 9, 'Alice i Eventyrland', 'DK', None, 'imdbDisplay', None, 0.0),
 ('tt10214198', 1, 'Gou yan kan ren xin', None, None, 'original', None, 1.0),
 ('tt10214198', 2, 'Push and Shove', None, None, None, None, 0.0),
 ('tt10214198', 3, 'Gou yan kan ren xin', 'CN', None, None, None, 0.0),
 ('tt10225354', 1, 'Volviendo a Casa', 'AR', None, None, None, 0.0),
 ('tt10225354', 2, 'Volviendo a Casa', None, None, 'original', None, 1.0),
 ('tt10225354', 3, 'Returning Home', 'XWW', 'en', 'alternative', None, 0.0),
 ('tt10225420', 1, 'El Universo En Que Te Amé', 'AR', None, None, None, 0.0),
 ('tt10225420',
  2,
  'The Universe in Which I Loved You',
  'XWW',
  'en',
  'imdbDisplay',
  None,
  0.0),
 ('tt10225420',
  3,
  'El Universo En Que Te Amé',
  None,
  None,
  'original',
  None,
  1.0),
 ('tt10308634', 1, 'My First Client', None, None, 'original', None, 1.0),
 ('tt10308634', 2, 'My First Client', 'KR', None, None, None, 0.0),
 ('tt10308634', 3, 'Young Clients', 'XWW', 'en', 'alternative', None, 0.0),
 ('tt10351180', 1, 'BadBoy', None, None, 'original', None, 1.0),
 ('tt10351180', 2, 'BadBoy', 'IN', None, None, None, 0.0),
 ('tt10351180', 3, 'Bad Boy', 'XWW', None, None, 'alternative spelling', 0.0),
 ('tt10379338', 1, 'Guys Night Out', 'US', None, 'imdbDisplay', None, 0.0),
 ('tt10379338', 2, 'Guys Night Out', None, None, 'original', None, 1.0),
 ('tt10379338', 3, 'Random Night Out', 'US', None, None, None, 0.0),
 ('tt10446418', 1, 'Icon', 'RS', None, None, None, 0.0),
 ('tt10446418', 2, 'Icon', None, None, 'original', None, 1.0),
 ('tt10446418', 3, 'The Icon', 'US', None, 'alternative', None, 0.0),
 ('tt1179034', 10, 'Armastusega Pariisist', 'EE', None, None, None, 0.0),
 ('tt1179034', 11, 'Dupla Implacável', 'BR', None, None, None, 0.0),
 ('tt1179034', 12, 'París en la Mira', 'MX', None, None, None, 0.0),
 ('tt1179034', 13, 'Sangre y amor en París', 'AR', None, None, None, 0.0),
 ('tt1179034', 14, 'From Paris with Love', 'FR', None, None, None, 0.0),
 ('tt1179034',
  15,
  'Desde París con amor',
  'ES',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 16, 'Из Парижа с любовью', 'RU', None, None, None, 0.0),
 ('tt1179034', 17, "MiParis be'ahava", 'IL', 'he', None, None, 0.0),
 ('tt1179034',
  18,
  'Linkejimai is Paryziaus',
  'LT',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 19, 'Bez soucitu', 'CZ', None, 'imdbDisplay', None, 0.0),
 ('tt1179034', 1, 'От Париж с любов', 'BG', 'bg', None, None, 0.0),
 ('tt1179034', 20, 'De Paris com Amor', 'PT', None, None, None, 0.0),
 ('tt1179034', 21, 'Από το Παρίσι με αγάπη', 'GR', None, None, None, 0.0),
 ('tt1179034',
  22,
  'From Paris with Love',
  'IT',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034',
  23,
  'Din Paris, cu dragoste',
  'RO',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 24, "Paris'ten sevgilerle", 'TR', 'tr', None, None, 0.0),
 ('tt1179034',
  25,
  'Iz Pariza s ljubavlju',
  'RS',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 26, 'Pozdrowienia z Paryza', 'PL', None, None, None, 0.0),
 ('tt1179034',
  27,
  'Bons baisers de Paris',
  'CA',
  'fr',
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 28, 'París en la mira', 'PE', None, None, None, 0.0),
 ('tt1179034',
  2,
  'Apo to Parisi me agapi',
  'GR',
  None,
  None,
  'transliterated ISO-LATIN-1 title',
  0.0),
 ('tt1179034',
  3,
  'Iz Pariza z ljubeznijo',
  'SI',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034', 4, "З Парижу з любов'ю", 'UA', None, None, None, 0.0),
 ('tt1179034', 5, 'From Paris with Love', None, None, 'original', None, 1.0),
 ('tt1179034',
  6,
  'Párizsból szeretettel',
  'HU',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034',
  7,
  'Sangre y amor en París',
  'CL',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034',
  8,
  'From Paris with Love',
  'DK',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1179034',
  9,
  'Iz Pariza s ljubavlju',
  'HR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1180174', 1, 'Liberty', 'US', None, None, None, 0.0),
 ('tt1182315', 1, 'Negro Buenos Aires', None, None, 'original', None, 1.0),
 ('tt1182315', 2, 'Black Buenos Aires', 'XWW', 'en', 'imdbDisplay', None, 0.0),
 ('tt1182315', 3, 'Negro Buenos Aires', 'ES', None, None, None, 0.0),
 ('tt1182315', 4, 'Dark Buenos Aires', 'US', None, 'imdbDisplay', None, 0.0),
 ('tt1189904', 1, 'Small Town Hero', 'US', None, None, None, 0.0),
 ('tt1194173', 10, 'Bornovo nasleđe', 'RS', None, None, None, 0.0),
 ('tt1194173',
  11,
  "Dziedzictwo Bourne'a",
  'PL',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 12, 'O Legado Bourne', 'BR', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 13, 'Наследството на Борн', 'BG', 'bg', None, None, 0.0),
 ('tt1194173',
  14,
  "Jason Bourne: L'héritage",
  'FR',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 15, "Bourne'un Mirasi", 'TR', 'tr', 'imdbDisplay', None, 0.0),
 ('tt1194173', 16, 'Bornas. Palikimas', 'LT', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 17, 'Η κληρονομιά του Μπορν', 'GR', None, None, None, 0.0),
 ('tt1194173', 18, 'Borna mantojums', 'LV', None, 'imdbDisplay', None, 0.0),
 ('tt1194173',
  19,
  'I klironomia tou Bourne',
  'GR',
  None,
  None,
  'transliterated ISO-LATIN-1 title',
  0.0),
 ('tt1194173', 1, 'Эволюция Борна', 'RU', None, None, None, 0.0),
 ('tt1194173', 20, 'O Legado de Bourne', 'PT', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 21, 'El Legado Bourne', 'CO', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 22, 'Bourneuv odkaz', 'CZ', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 23, 'A Bourne-hagyaték', 'HU', None, 'imdbDisplay', None, 0.0),
 ('tt1194173',
  24,
  'El legado de Bourne',
  'ES',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 25, 'Bourneovo nasljeđe', 'HR', None, None, None, 0.0),
 ('tt1194173', 26, 'Zehut gnuva', 'IL', 'he', 'imdbDisplay', None, 0.0),
 ('tt1194173',
  27,
  'Das Bourne Vermächtnis',
  'DE',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 28, 'Спадок Борна', 'UA', None, None, None, 0.0),
 ('tt1194173', 29, 'El legado Bourne', 'PE', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 2, 'Marcher', 'US', None, None, 'fake working title', 0.0),
 ('tt1194173',
  30,
  "La peur dans la peau: L'héritage de Bourne",
  'CA',
  'fr',
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 31, 'El legado Bourne', 'UY', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 32, 'The Bourne Legacy', None, None, 'original', None, 1.0),
 ('tt1194173', 3, 'El Legado Bourne', 'MX', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 4, 'El legado Bourne', 'CL', None, 'imdbDisplay', None, 0.0),
 ('tt1194173',
  5,
  'Mostenirea lui Bourne',
  'RO',
  None,
  'imdbDisplay',
  None,
  0.0),
 ('tt1194173', 6, 'El legado Bourne', 'AR', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 7, "Bourne'i pärand", 'EE', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 8, 'Medusan perintö', 'FI', None, 'imdbDisplay', None, 0.0),
 ('tt1194173', 9, 'The Bourne Legacy', 'US', None, None, None, 0.0),
 ('tt1210047',
  1,
  'Snatched! Curse of the Pink Panties 2',
  'US',
  None,
  'alternative',
  None,
  0.0),
 ('tt1210047', 2, 'Snatched!', None, None, 'original', None, 1.0),
 ('tt1210047',
  3,
  'Curse of the Pink Panties II',
  'US',
  None,
  'working',
  None,
  0.0),
 ('tt1210047', 4, 'Snatched!', 'US', None, None, None, 0.0),
 ('tt1219289', 10, 'Sin Límites', 'AR', None, 'imdbDisplay', None, 0.0),
 ('tt1219289', 11, 'Bezgranicno', 'BA', 'hr', 'imdbDisplay', None, 0.0),
 ('tt1219289', 12, 'Csúcshatás', 'HU', None, 'imdbDisplay', None, 0.0),
 ('tt1219289', 13, 'Kõrvalnähud', 'EE', None, 'imdbDisplay', None, 0.0),
 ('tt1219289', 14, 'The Dark Fields', 'US', None, 'working', None, 0.0),
 ('tt1219289', 15, 'Ohne Limit', 'DE', None, 'imdbDisplay', None, 0.0),
 ('tt1219289', 16, 'Sin límites', 'PE', None, 'imdbDisplay', None, 0.0),
 ('tt1219289', 17, 'Všemocný', 'CZ', None, None, None, 0.0),
 ('tt1219289', 18, 'Απόλυτη ευφυΐα', 'GR', None, None, None, 0.0),
 ('tt1219289', 19, 'Limitless', None, None, 'original', None, 1.0),
 ('tt1219289', 1, 'Lelo gvulot', 'IL', 'he', None, None, 0.0),

In [17]:
cur.execute('''SELECT * FROM movie_ratings''');
cur.fetchall()

[('tt10356526', 8.3, 31),
 ('tt10384606', 8.9, 559),
 ('tt1042974', 6.4, 20),
 ('tt1043726', 4.2, 50352),
 ('tt1060240', 6.5, 21),
 ('tt1069246', 6.2, 326),
 ('tt1094666', 7.0, 1613),
 ('tt1130982', 6.4, 571),
 ('tt1156528', 7.2, 265),
 ('tt1161457', 4.2, 148),
 ('tt1171222', 5.1, 8296),
 ('tt1174693', 5.8, 2381),
 ('tt1181840', 7.0, 5494),
 ('tt1193623', 8.0, 5),
 ('tt1199588', 5.5, 74),
 ('tt1204784', 5.8, 6),
 ('tt1210166', 7.6, 326657),
 ('tt1212419', 6.5, 87288),
 ('tt1220911', 5.0, 941),
 ('tt1229238', 7.4, 428142),
 ('tt1232829', 7.2, 477771),
 ('tt1235548', 6.6, 2725),
 ('tt1243974', 5.4, 54646),
 ('tt1250861', 6.2, 416),
 ('tt1258812', 4.0, 21),
 ('tt1261945', 4.4, 69199),
 ('tt1266037', 7.0, 1413),
 ('tt1270291', 5.8, 5728),
 ('tt1270761', 5.6, 44490),
 ('tt1272886', 6.1, 6688),
 ('tt1274297', 5.4, 381),
 ('tt1283887', 5.4, 2527),
 ('tt1285219', 3.4, 387),
 ('tt1287879', 7.7, 76),
 ('tt1290476', 7.2, 6),
 ('tt1294141', 4.5, 113),
 ('tt1320239', 6.2, 18431),
 ('tt1322312', 6.3, 54421),
 ('tt1323962', 5.1, 101),
 ('tt1325014', 6.7, 4240),
 ('tt1325019', 7.2, 29),
 ('tt1326743', 8.4, 21),
 ('tt1327602', 7.8, 8),
 ('tt1328913', 5.2, 738),
 ('tt1331329', 3.6, 1621),
 ('tt1332570', 2.1, 17),
 ('tt1343110', 2.5, 345),
 ('tt1343740', 4.6, 495),
 ('tt1346690', 7.7, 7),
 ('tt1352393', 7.7, 1293),
 ('tt1358596', 7.7, 6),
 ('tt1360829', 5.0, 223),
 ('tt1368858', 5.4, 4302),
 ('tt1374988', 6.1, 163),
 ('tt1376213', 5.4, 5257),
 ('tt1378667', 7.5, 31),
 ('tt1379736', 5.7, 15),
 ('tt1381418', 5.4, 6220),
 ('tt1400515', 3.5, 1701),
 ('tt1403981', 7.1, 129443),
 ('tt1403990', 8.5, 31),
 ('tt1404830', 5.3, 1768),
 ('tt1409015', 8.2, 40),
 ('tt1417086', 7.5, 197),
 ('tt1418760', 6.4, 1502),
 ('tt1420547', 6.1, 16),
 ('tt1422020', 7.0, 10025),
 ('tt1426379', 3.8, 9),
 ('tt1426385', 4.9, 19),
 ('tt1428464', 6.4, 227),
 ('tt1438493', 6.3, 86),
 ('tt1443518', 5.5, 297),
 ('tt1447483', 6.9, 28),
 ('tt1450750', 8.6, 27),
 ('tt1456110', 6.5, 60),
 ('tt1460739', 7.3, 354),
 ('tt1460743', 6.9, 6990),
 ('tt1465505', 6.4, 5273),
 ('tt1465519', 4.7, 1497),
 ('tt1467290', 6.3, 173),
 ('tt1468387', 6.5, 2306),
 ('tt1474456', 3.2, 103),
 ('tt1478277', 2.6, 102),
 ('tt1479320', 5.6, 143),
 ('tt1480670', 5.2, 303),
 ('tt1486670', 4.7, 3713),
 ('tt1488109', 8.2, 14),
 ('tt1492849', 5.2, 534),
 ('tt1494611', 7.3, 102),
 ('tt1499658', 6.9, 398695),
 ('tt1508689', 4.7, 16),
 ('tt1510989', 3.9, 83),
 ('tt1512098', 5.9, 33),
 ('tt1512102', 5.9, 67),
 ('tt1512893', 3.4, 212),
 ('tt1515069', 8.3, 15),
 ('tt1515208', 6.3, 1447),
 ('tt1516577', 5.3, 147),
 ('tt1516595', 4.4, 64),
 ('tt1517225', 7.4, 2189),
 ('tt1517605', 8.7, 23),
 ('tt1521782', 6.8, 19),
 ('tt1527710', 7.7, 29),
 ('tt1527723', 7.3, 9),
 ('tt1527821', 6.1, 160),
 ('tt1528274', 7.8, 11),
 ('tt1534084', 4.5, 875),
 ('tt1535109', 7.8, 387402),
 ('tt1535491', 7.0, 3218),
 ('tt1535611', 6.8, 20),
 ('tt1537385', 8.0, 53),
 ('tt1538545', 5.8, 821),
 ('tt1538833', 7.2, 395),
 ('tt1538988', 7.1, 224),
 ('tt1539042', 5.5, 382),
 ('tt1539491', 5.6, 55),
 ('tt1540074', 7.9, 71),
 ('tt1545489', 4.9, 137),
 ('tt1547032', 7.0, 7),
 ('tt1549572', 7.0, 85839),
 ('tt1555056', 6.8, 20),
 ('tt1555187', 2.0, 164),
 ('tt1558741', 5.1, 430),
 ('tt1559035', 7.5, 34),
 ('tt1560962', 6.0, 7),
 ('tt1562295', 7.0, 36),
 ('tt1563121', 3.7, 40),
 ('tt1564368', 4.7, 1522),
 ('tt1564870', 5.6, 614),
 ('tt1569505', 6.1, 231),
 ('tt1570962', 5.8, 172),
 ('tt1571416', 7.9, 75),
 ('tt1575538', 8.2, 5),
 ('tt1575695', 6.9, 14),
 ('tt1580346', 6.9, 212),
 ('tt1582507', 5.6, 66303),
 ('tt1582546', 7.4, 2137),
 ('tt1583743', 7.3, 100),
 ('tt1584131', 3.7, 1071),
 ('tt1584146', 3.4, 186),
 ('tt1587107', 4.0, 8),
 ('tt1587699', 7.0, 79),
 ('tt1592528', 5.9, 30),
 ('tt1592531', 5.9, 32),
 ('tt1593726', 5.8, 44),
 ('tt1595379', 7.4, 14),
 ('tt1595637', 2.4, 310),
 ('tt1600197', 3.0, 349),
 ('tt1603379', 3.5, 102),
 ('tt1604709', 5.1, 15),
 ('tt1606215', 5.6, 118),
 ('tt1606706', 7.3, 63),
 ('tt1608246', 8.0, 26),
 ('tt1608290', 4.7, 59914),
 ('tt1608345', 8.4, 34),
 ('tt1609150', 5.4, 36),
 ('tt1611878', 7.8, 10),
 ('tt1612608', 5.8, 1360),
 ('tt1614963', 8.1, 9),
 ('tt1615477', 6.8, 23),
 ('tt1615840', 6.6, 578),
 ('tt1615902', 5.4, 116),
 ('tt1618467', 7.5, 84),
 ('tt1620785', 7.1, 640),
 ('tt1624411', 5.6, 32),
 ('tt1625155', 7.4, 1636),
 ('tt1628022', 7.8, 5),
 ('tt1628043', 5.4, 195),
 ('tt1629739', 7.3, 23),
 ('tt1629757', 7.2, 28994),
 ('tt1630311', 4.8, 32),
 ('tt1630607', 3.5, 210),
 ('tt1633248', 5.7, 56),
 ('tt1633334', 8.4, 11),
 ('tt1635429', 5.7, 110),
 ('tt1639427', 6.3, 137),
 ('tt1640219', 2.8, 114),
 ('tt1640484', 5.7, 9089),
 ('tt1642248', 5.6, 64),
 ('tt1645141', 5.8, 148),
 ('tt1647446', 5.5, 86),
 ('tt1650516', 3.4, 491),
 ('tt1650533', 7.4, 88),
 ('tt1651906', 9.2, 9),
 ('tt1655416', 6.2, 4670),
 ('tt1655420', 7.0, 79337),
 ('tt1659253', 6.5, 1603),
 ('tt1659343', 5.1, 18206),
 ('tt1660393', 5.7, 63),
 ('tt1661420', 7.3, 12506),
 ('tt1662557', 7.4, 4869),
 ('tt1662615', 7.0, 46),
 ('tt1662634', 7.2, 430),
 ('tt1663202', 8.0, 621193),
 ('tt1664837', 8.3, 25),
 ('tt1665807', 7.2, 6),
 ('tt1667417', 3.7, 484),
 ('tt1668191', 7.5, 27146),
 ('tt1671494', 5.6, 136),
 ('tt1671509', 6.8, 23),
 ('tt1671513', 7.8, 2553),
 ('tt1671714', 7.1, 13),
 ('tt1671728', 8.5, 21),
 ('tt1673732', 8.0, 20),
 ('tt1674746', 6.6, 10),
 ('tt1676132', 7.7, 6),
 ('tt1678037', 4.4, 275),
 ('tt1678052', 5.2, 349),
 ('tt1679290', 6.1, 108),
 ('tt1680045', 6.2, 15096),
 ('tt1681370', 5.3, 195),
 ('tt1682178', 6.9, 138),
 ('tt1683040', 6.5, 2826),
 ('tt1683919', 4.3, 73),
 ('tt1686326', 4.8, 113),
 ('tt1693106', 5.8, 48),
 ('tt1695793', 5.8, 395),
 ('tt1700274', 8.1, 9),
 ('tt1701202', 7.6, 78),
 ('tt1702016', 4.2, 757),
 ('tt1703923', 6.0, 657),
 ('tt1703958', 5.8, 5997),
 ('tt1705877', 6.6, 52),
 ('tt1706450', 6.6, 3321),
 ('tt1709653', 5.6, 602),
 ('tt1709657', 8.1, 75),
 ('tt1709714', 6.7, 75),
 ('tt1713439', 6.0, 9),
 ('tt1714206', 7.1, 133887),
 ('tt1715352', 2.9, 257),
 ('tt1716746', 7.7, 6),
 ('tt1717690', 6.5, 86),
 ('tt1717736', 7.2, 8),
 ('tt1719496', 6.4, 160),
 ('tt1719671', 6.9, 18),
 ('tt1720161', 6.4, 10),
 ('tt1720293', 6.4, 51),
 ('tt1721131', 6.4, 13),
 ('tt1721494', 6.1, 458),
 ('tt1721680', 6.9, 15),
 ('tt1725995', 7.6, 2309),
 ('tt1726589', 5.6, 7229),
 ('tt1726661', 5.2, 422),
 ('tt1727519', 4.1, 458),
 ('tt1728196', 7.4, 6636),
 ('tt1728217', 4.6, 668),
 ('tt1728986', 5.5, 7359),
 ('tt1729218', 6.0, 623),
 ('tt1729659', 7.7, 10),
 ('tt1733578', 3.8, 2280),
 ('tt1734163', 7.5, 147),
 ('tt1735350', 4.2, 232),
 ('tt1735485', 5.9, 18038),
 ('tt1735495', 6.9, 105),
 ('tt1735952', 6.9, 8),
 ('tt1736000', 1.4, 5),
 ('tt1737724', 6.1, 81),
 ('tt1740056', 5.5, 52),
 ('tt1740117', 8.7, 60),
 ('tt1740539', 1.9, 636),
 ('tt1740684', 6.1, 76),
 ('tt1745959', 4.9, 56),
 ('tt1748055', 8.7, 6),
 ('tt1748157', 7.9, 7),
 ('tt1748212', 7.3, 9),
 ('tt1753471', 5.6, 55),
 ('tt1753577', 7.8, 9),
 ('tt1753584', 5.3, 3526),
 ('tt1753602', 7.8, 18),
 ('tt1753728', 7.9, 8),
 ('tt1753780', 7.8, 11),
 ('tt1754602', 7.8, 5),
 ('tt1754649', 5.5, 13),
 ('tt1754750', 4.8, 158),
 ('tt1754950', 6.2, 5),
 ('tt1756828', 3.4, 9),
 ('tt1758611', 8.7, 15),
 ('tt1758741', 6.4, 13),
 ('tt1758842', 5.6, 41),
 ('tt1759727', 7.3, 18),
 ('tt1763217', 6.3, 289),
 ('tt1764164', 6.2, 6),
 ('tt1764311', 5.9, 24),
 ('tt1764500', 7.6, 8),
 ('tt1765868', 8.8, 5),
 ('tt1766009', 5.4, 24),
 ('tt1766044', 7.0, 468),
 ('tt1770757', 4.2, 8),
 ('tt1772275', 3.6, 7),
 ('tt1773528', 7.8, 9),
 ('tt1773607', 7.7, 19),
 ('tt1773790', 6.0, 8),
 ('tt1776201', 5.3, 427),
 ('tt1779471', 7.8, 156),
 ('tt1780934', 7.8, 10),
 ('tt1782562', 6.7, 14),
 ('tt1783311', 6.1, 799),
 ('tt1783377', 7.0, 848),
 ('tt1783384', 6.8, 37),
 ('tt1783392', 5.0, 447),
 ('tt1783393', 7.0, 87),
 ('tt1785525', 7.9, 9),
 ('tt1786411', 6.9, 16),
 ('tt1786652', 8.0, 27),
 ('tt1787047', 5.8, 19),
 ('tt1787741', 4.2, 12),
 ('tt1787777', 6.9, 3159),
 ('tt1789077', 6.5, 17),
 ('tt1791681', 3.9, 1890),
 ('tt1792647', 6.8, 7643),
 ('tt1792801', 5.9, 18),
 ('tt1793223', 5.6, 1969),
 ('tt1793290', 6.5, 6),
 ('tt1793296', 6.1, 8),
 ('tt1796580', 7.5, 42),
 ('tt1796652', 7.5, 1503),
 ('tt1797449', 6.1, 878),
 ('tt1798162', 6.3, 16),
 ('tt1798164', 5.4, 27),
 ('tt1801512', 6.2, 6),
 ('tt1802827', 8.9, 19),
 ('tt1808197', 6.5, 10445),
 ('tt1808208', 4.0, 425),
 ('tt1810756', 4.4, 10),
 ('tt1813152', 8.6, 7),
 ('tt1814768', 7.6, 16),
 ('tt1815605', 4.3, 9),
 ('tt1815707', 6.9, 65),
 ('tt1815836', 6.9, 240),
 ('tt1817711', 6.3, 56),
 ('tt0758752', 6.7, 167680),
 ('tt0775461', 5.4, 70),
 ('tt0800054', 7.8, 68),
 ('tt0800092', 4.3, 6),
 ('tt0816362', 6.7, 223),
 ('tt0825282', 6.5, 121),
 ('tt0960864', 7.0, 109),
 ('tt0978812', 6.4, 9),
 ('tt0979434', 5.0, 10042),
 ('tt0985694', 6.6, 182320),
 ('tt10062286', 5.9, 14),
 ('tt10075374', 8.3, 6),
 ('tt10174464', 7.3, 7),
 ('tt10243678', 6.5, 1394),
 ('tt10254986', 7.0, 15),
 ('tt6494520', 4.3, 12),
 ('tt6500762', 6.0, 25),
 ('tt6505826', 5.5, 130),
 ('tt6506146', 5.0, 670),
 ('tt6522546', 6.8, 7930),
 ('tt6523386', 6.9, 117),
 ('tt6547822', 3.7, 26),
 ('tt6555772', 5.8, 1826),
 ('tt6558114', 4.8, 221),
 ('tt6579530', 4.8, 28),
 ('tt6582734', 6.4, 68),
 ('tt6589292', 6.0, 246),
 ('tt6590978', 8.0, 36),
 ('tt6594022', 3.9, 94),
 ('tt6594148', 5.4, 31),
 ('tt6597044', 6.2, 6),
 ('tt6599256', 8.3, 116),
 ('tt6612178', 7.9, 35),
 ('tt6634906', 7.6, 14),
 ('tt6636878', 7.9, 9),
 ('tt6677500', 4.5, 223),
 ('tt6679412', 6.2, 959),
 ('tt6688136', 5.9, 2615),
 ('tt6704014', 6.6, 83),
 ('tt6705988', 8.1, 16),
 ('tt6710772', 7.4, 50),
 ('tt6712026', 7.1, 1598),
 ('tt6720674', 6.5, 27),
 ('tt6725484', 7.1, 590),
 ('tt6730644', 6.5, 8),
 ('tt6731592', 7.9, 95),
 ('tt6737494', 8.9, 23),
 ('tt6742252', 7.5, 25267),
 ('tt6745192', 6.8, 12),
 ('tt6749456', 8.9, 12),
 ('tt6750506', 5.9, 119),
 ('tt6751046', 7.6, 18),
 ('tt6764122', 7.1, 308),
 ('tt6769280', 5.7, 3455),
 ('tt6778706', 7.9, 11),
 ('tt6780706', 9.4, 18),
 ('tt6806804', 7.6, 7),
 ('tt6808782', 5.9, 12),
 ('tt6828530', 6.3, 132),
 ('tt6831278', 7.0, 5),
 ('tt6844416', 6.4, 7),
 ('tt6845800', 8.2, 9),
 ('tt6850078', 9.2, 18),
 ('tt6854248', 6.6, 1454),
 ('tt6857040', 4.6, 731),
 ('tt6857298', 5.2, 5),
 ('tt6858020', 6.1, 308),
 ('tt6866652', 3.3, 34),
 ('tt6867356', 9.1, 9),
 ('tt6870220', 8.6, 5),
 ('tt6871240', 8.2, 5),
 ('tt6888762', 7.9, 10),
 ('tt6892088', 7.8, 10),
 ('tt6901904', 7.6, 7),
 ('tt6910380', 7.5, 37),
 ('tt6920930', 4.6, 91),
 ('tt6922138', 9.2, 17),
 ('tt6925132', 5.4, 5),
 ('tt6925204', 5.4, 14),
 ('tt6936264', 6.2, 6),
 ('tt6943606', 8.0, 9),
 ('tt6947800', 6.9, 93),
 ('tt6954970', 8.2, 6),
 ('tt6955130', 6.1, 41),
 ('tt6982394', 7.9, 8),
 ('tt6983064', 6.7, 6),
 ('tt6998228', 5.9, 99),
 ('tt7004152', 7.0, 88),
 ('tt7008774', 4.5, 6),
 ('tt7012864', 6.3, 1490),
 ('tt7021436', 7.3, 17),
 ('tt7024660', 8.1, 26),
 ('tt7026270', 8.1, 28),
 ('tt7027278', 6.0, 4189),
 ('tt7030048', 5.2, 22),
 ('tt7056470', 6.8, 33),
 ('tt7063474', 7.9, 10),
 ('tt7076838', 5.6, 57),
 ('tt7089878', 7.2, 503),
 ('tt7093188', 8.2, 24),
 ('tt7108862', 3.7, 145),
 ('tt7112166', 5.4, 31),
 ('tt7122516', 7.5, 13),
 ('tt7134214', 7.5, 16),
 ('tt7142712', 7.1, 114),
 ('tt7149066', 6.5, 39),
 ('tt7158582', 7.4, 439),
 ('tt7158686', 5.1, 873),
 ('tt7164084', 6.9, 11),
 ('tt7166214', 6.8, 185),
 ('tt7185492', 3.7, 423),
 ('tt7198146', 8.0, 5),
 ('tt7205630', 6.0, 601),
 ('tt7208564', 5.3, 2972),
 ('tt7211010', 7.6, 144),
 ('tt7217128', 5.7, 176),
 ('tt7223050', 5.6, 398),
 ('tt7225716', 4.0, 15),
 ('tt7228676', 4.1, 9),
 ('tt7239688', 7.3, 28),
 ('tt7254768', 7.0, 36),
 ('tt7256866', 5.2, 7728),
 ('tt7259100', 5.1, 160),
 ('tt7262052', 6.6, 299),
 ('tt7269624', 7.0, 7),
 ('tt7274816', 3.7, 7),
 ('tt7275980', 5.1, 28),
 ('tt7277330', 8.6, 5),
 ('tt7290740', 6.3, 40),
 ('tt7293844', 7.2, 26),
 ('tt7293920', 6.8, 20),
 ('tt7298028', 9.1, 28),
 ('tt7305634', 7.9, 35),
 ('tt7313218', 6.7, 87),
 ('tt7315526', 4.9, 1466),
 ('tt7315648', 6.0, 27),
 ('tt7316206', 5.9, 35),
 ('tt7323332', 6.0, 195),
 ('tt7341988', 4.8, 32),
 ('tt7342204', 7.4, 1105),
 ('tt7345928', 6.5, 57),
 ('tt7361790', 4.9, 13),
 ('tt7363356', 7.2, 10),
 ('tt7370188', 6.9, 310),
 ('tt7374968', 6.8, 43),
 ('tt7375556', 5.4, 115),
 ('tt7382572', 6.4, 44),
 ('tt7385518', 7.4, 18),
 ('tt7385580', 8.5, 14),
 ('tt7388694', 6.5, 24),
 ('tt7389918', 7.3, 6),
 ('tt7390044', 6.4, 69),
 ('tt7390380', 7.0, 54),
 ('tt7399124', 7.1, 410),
 ('tt7403574', 5.1, 81),
 ('tt7404894', 6.7, 9),
 ('tt7407950', 6.9, 19),
 ('tt7411202', 8.8, 10),
 ('tt7412738', 6.3, 793),
 ('tt7416102', 5.2, 50),
 ('tt7418296', 6.1, 7),
 ('tt7419468', 6.3, 236),
 ('tt7421764', 5.4, 7),
 ('tt7424410', 4.2, 103),
 ('tt7429318', 7.1, 46),
 ('tt7429708', 6.2, 867),
 ('tt7433980', 6.8, 110),
 ('tt7436642', 7.7, 1842),
 ('tt7446940', 4.3, 6),
 ('tt7451284', 5.6, 13943),
 ('tt7457108', 5.1, 51),
 ('tt7460834', 7.9, 26),
 ('tt7461982', 8.5, 6),
 ('tt7467324', 6.6, 377),
 ('tt7469978', 5.2, 151),
 ('tt7470398', 8.0, 5),
 ('tt7475708', 7.2, 22),
 ('tt7484546', 5.6, 9),
 ('tt7520478', 3.6, 13),
 ('tt7521000', 6.4, 75),
 ('tt7521846', 4.3, 289),
 ('tt7524472', 6.8, 8),
 ('tt7526316', 6.9, 23),
 ('tt7526492', 8.2, 93),
 ('tt7533152', 7.6, 10725),
 ('tt7533756', 7.0, 200),
 ('tt7541970', 9.7, 6),
 ('tt7542576', 5.8, 1054),
 ('tt7542928', 7.4, 12),
 ('tt7553526', 8.3, 13),
 ('tt7558166', 5.6, 85),
 ('tt7569402', 9.0, 7),
 ('tt7572744', 7.3, 340),
 ('tt7575400', 2.7, 55),
 ('tt7592540', 8.3, 7),
 ('tt7600780', 7.5, 8),
 ('tt7603154', 8.3, 14),
 ('tt7604636', 5.9, 14),
 ('tt7606796', 7.8, 33),
 ('tt7606826', 5.8, 6),
 ('tt7610008', 8.0, 921),
 ('tt7620732', 3.6, 37),
 ('tt7628458', 7.2, 2218),
 ('tt7631320', 3.6, 168),
 ('tt7632870', 6.5, 8),
 ('tt7639236', 6.7, 6),
 ('tt7674116', 8.9, 14),
 ('tt7675596', 6.7, 14),
 ('tt7686386', 5.0, 72),
 ('tt7689964', 7.5, 8071),
 ('tt7690670', 5.0, 4753),
 ('tt7693236', 7.9, 19),
 ('tt7708146', 5.4, 138),
 ('tt7710836', 6.6, 7),
 ('tt7730492', 5.8, 116),
 ('tt7748852', 8.3, 20),
 ('tt7752880', 6.1, 38),
 ('tt7762194', 1.0, 67),
 ('tt7766166', 5.7, 7),
 ('tt7770192', 5.7, 725),
 ('tt7770232', 7.7, 45),
 ('tt7783776', 6.2, 29),
 ('tt7791218', 6.4, 464),
 ('tt7794400', 8.3, 36),
 ('tt7802246', 8.2, 38),
 ('tt7809214', 4.3, 26),
 ('tt7817234', 3.1, 17),
 ('tt7820502', 5.8, 38),
 ('tt7822320', 7.2, 388),
 ('tt7827728', 6.0, 9),
 ('tt7848100', 7.6, 26),
 ('tt7852572', 9.0, 5),
 ('tt7858220', 7.2, 12),
 ('tt7868256', 8.8, 13),
 ('tt7882250', 6.2, 83),
 ('tt7891828', 6.4, 7),
 ('tt7894140', 8.4, 5),
 ('tt7895368', 9.0, 7),
 ('tt7921282', 7.1, 80),
 ('tt7928214', 6.3, 56),
 ('tt7929502', 7.2, 5),
 ('tt7948406', 9.1, 12),
 ('tt7955106', 8.0, 283),
 ('tt7958740', 7.5, 87),
 ('tt7963218', 1.7, 597),
 ('tt7971756', 7.2, 27),
 ('tt7972100', 5.6, 7),
 ('tt7976486', 7.0, 85),
 ('tt7976502', 4.4, 112),
 ('tt7977310', 6.6, 42),
 ('tt7984730', 8.8, 203),
 ('tt7989520', 8.4, 5),
 ('tt8001954', 6.8, 10),
 ('tt8019076', 6.1, 8),
 ('tt8026954', 7.5, 19),
 ('tt8041618', 8.1, 46),
 ('tt8045100', 8.5, 6),
 ('tt8058904', 5.9, 126),
 ('tt8064342', 5.5, 106),
 ('tt8071724', 7.0, 5),
 ('tt8076344', 7.3, 579),
 ('tt8096198', 8.7, 15),
 ('tt8103460', 3.1, 16),
 ('tt8106590', 9.0, 9),
 ('tt8108194', 7.3, 6),
 ('tt8108198', 8.5, 43409),
 ('tt8108208', 6.2, 1420),
 ('tt8108212', 7.1, 46),
 ('tt8110450', 4.2, 5),
 ('tt8110590', 7.9, 7),
 ('tt8128672', 5.5, 89),
 ('tt8129312', 4.2, 6),
 ('tt8129666', 8.6, 8),
 ('tt8142462', 6.6, 17),
 ('tt8144954', 7.3, 38),
 ('tt8171974', 6.2, 180),
 ('tt8196200', 7.9, 66),
 ('tt8209632', 5.5, 24),
 ('tt8220332', 3.8, 295),
 ('tt8236398', 6.3, 144),
 ('tt8260954', 5.9, 17),
 ('tt8269378', 6.7, 176),
 ('tt8286436', 7.3, 7),
 ('tt8294696', 9.2, 22),
 ('tt8320168', 8.0, 6),
 ('tt8322828', 6.0, 193),
 ('tt8346446', 6.9, 183),
 ('tt8356200', 6.9, 14),
 ('tt8359842', 7.7, 70),
 ('tt8383694', 6.1, 24),
 ('tt8387376', 5.1, 10),
 ('tt8396232', 6.6, 12),
 ('tt8396486', 7.5, 11),
 ('tt8401098', 7.8, 13),
 ('tt8420672', 2.4, 70),
 ('tt8423080', 8.1, 81),
 ('tt8426644', 7.9, 10),
 ('tt8430866', 8.1, 68),
 ('tt8475490', 8.5, 19),
 ('tt8503170', 6.6, 23),
 ('tt8503240', 7.6, 11),
 ('tt8508676', 7.3, 7),
 ('tt8510324', 5.6, 975),
 ('tt8526530', 2.3, 29),
 ('tt8539876', 9.5, 6),
 ('tt8550652', 6.7, 45),
 ('tt8556014', 7.9, 25),
 ('tt8558596', 4.8, 88),
 ('tt8569390', 6.3, 168),
 ('tt8579840', 5.5, 27),
 ('tt8580948', 8.8, 33),
 ('tt8587122', 6.0, 278),
 ('tt8593814', 9.3, 50),
 ('tt8602902', 7.8, 5),
 ('tt8609374', 5.1, 30),
 ('tt8617648', 3.8, 163),
 ('tt8653640', 8.3, 13),
 ('tt8660466', 5.9, 8),
 ('tt8679160', 6.7, 30),
 ('tt8682630', 8.9, 23),
 ('tt8682932', 5.8, 5),
 ('tt8684786', 5.5, 22),
 ('tt8698560', 6.5, 44),
 ('tt8705364', 8.5, 6),
 ('tt8714366', 7.3, 15),
 ('tt8718066', 7.2, 20),
 ('tt8722030', 1.7, 28),
 ('tt8756098', 7.2, 26),
 ('tt8763008', 5.7, 254),
 ('tt8769370', 5.6, 5),
 ('tt8793222', 9.0, 6),
 ('tt8814978', 6.3, 22),
 ('tt8820198', 8.4, 16),
 ('tt8828434', 7.7, 72),
 ('tt8835552', 7.0, 143),
 ('tt8837044', 5.1, 152),
 ('tt8842320', 6.5, 19),
 ('tt8852242', 7.3, 45),
 ('tt8857350', 6.8, 12),
 ('tt8883524', 6.9, 48),
 ('tt8886288', 6.8, 9),
 ('tt8903540', 8.2, 5),
 ('tt8933330', 3.7, 12),
 ('tt8976472', 6.6, 27),
 ('tt8977440', 2.3, 25),
 ('tt8996488', 7.8, 5),
 ('tt8997034', 5.2, 38),
 ('tt9001652', 9.2, 8),
 ('tt9015764', 6.7, 32),
 ('tt9024664', 7.1, 41),
 ('tt9025292', 8.4, 5),
 ('tt9053030', 7.2, 17),
 ('tt9061192', 7.5, 8),
 ('tt9080630', 2.1, 112),
 ('tt9088588', 7.3, 40),
 ('tt9094980', 7.0, 45),
 ('tt9114436', 6.7, 37),
 ('tt9115662', 6.4, 12),
 ('tt9118870', 6.7, 504),
 ('tt9130246', 8.6, 558),
 ('tt9139040', 7.9, 46),
 ('tt9141128', 7.1, 295),
 ('tt9154776', 3.0, 30),
 ('tt9159000', 6.5, 12),
 ('tt9190740', 8.3, 39),
 ('tt9204352', 6.4, 201),
 ('tt9233172', 8.1, 8),
 ('tt9249222', 9.0, 5),
 ('tt9310460', 5.9, 43),
 ('tt9353436', 7.6, 36),
 ('tt9356320', 7.3, 6),
 ('tt9358044', 6.8, 628),
 ('tt9358256', 7.3, 79),
 ('tt9359942', 7.2, 5),
 ('tt9363366', 8.7, 7),
 ('tt9447768', 7.1, 7),
 ('tt9450542', 4.0, 99),
 ('tt9529752', 1.7, 20),
 ('tt9562694', 2.6, 1509),
 ('tt9567548', 7.8, 327),
 ('tt9593792', 6.1, 39),
 ('tt9644084', 5.2, 5),
 ('tt9648942', 6.7, 403),
 ('tt9657946', 6.0, 16),
 ('tt9659470', 4.5, 456),
 ('tt9703880', 7.5, 23),
 ('tt9723084', 6.7, 35),
 ('tt9726638', 6.0, 6),
 ('tt9762928', 5.9, 15),
 ('tt9800694', 5.4, 7),
 ('tt9827784', 7.7, 6),
 ('tt9833362', 8.4, 7),
 ('tt9838372', 5.7, 46),
 ('tt9845012', 8.0, 10),
 ('tt9865446', 8.5, 32),
 ('tt0066787', 7.2, 43),
 ('tt0844699', 9.0, 5),
 ('tt0844915', 7.5, 56),
 ('tt0847735', 4.5, 15),
 ('tt0879870', 5.8, 77709),
 ('tt0892318', 6.6, 86137),
 ('tt0959329', 5.5, 11358),
 ('tt0960067', 6.9, 83),
 ('tt0988655', 4.7, 185),
 ('tt10011448', 9.4, 7),
 ('tt10016532', 6.1, 152),
 ('tt10066162', 6.5, 88),
 ('tt10078894', 2.3, 30),
 ('tt10122038', 7.6, 78),
 ('tt1015471', 6.2, 1888),
 ('tt10179072', 6.1, 10),
 ('tt10204316', 7.6, 5),
 ('tt1020982', 6.6, 147),
 ('tt10262346', 6.3, 7),
 ('tt10308686', 9.3, 15),
 ('tt10312668', 8.9, 2111),
 ('tt10338308', 7.0, 74),
 ('tt1053835', 6.2, 348),
 ('tt1071783', 4.7, 64),
 ('tt1071872', 7.1, 33),
 ('tt1079964', 5.0, 576),
 ('tt1091212', 6.5, 338),
 ('tt1092634', 6.4, 8662),
 ('tt1111900', 7.8, 12),
 ('tt1127897', 5.4, 352),
 ('tt1137473', 7.7, 6),
 ('tt1183352', 6.7, 415),
 ('tt1193626', 6.8, 166),
 ('tt1201607', 8.1, 691835),
 ('tt1225703', 6.0, 453),
 ('tt1228705', 7.0, 657690),
 ('tt1230120', 5.5, 12),
 ('tt1232775', 6.4, 483),
 ('tt1232828', 5.9, 50),
 ('tt1235430', 6.3, 31),
 ('tt1247673', 5.1, 182),
 ('tt1274639', 5.5, 137),
 ('tt1277373', 6.2, 156),
 ('tt1279105', 4.1, 127),
 ('tt1282100', 6.7, 9),
 ('tt1285240', 5.6, 1321),
 ('tt1294212', 5.6, 263),
 ('tt1296881', 5.2, 576),
 ('tt1298655', 8.5, 6),
 ('tt1303680', 3.8, 200),
 ('tt1316033', 4.9, 16),
 ('tt1329320', 7.8, 31),
 ('tt1332110', 4.4, 229),
 ('tt1338705', 2.6, 41),
 ('tt1345444', 6.7, 173),
 ('tt1345505', 6.1, 127),
 ('tt1345834', 7.1, 547),
 ('tt1352380', 6.7, 740),
 ('tt1362518', 7.2, 437),
 ('tt1363368', 6.9, 27),

In [20]:
df_ratings=pd.read_sql_query('''SELECT * FROM movie_ratings''',con)
print(df_ratings)

         movie_id  averagerating  numvotes
0      tt10356526            8.3        31
1      tt10384606            8.9       559
2       tt1042974            6.4        20
3       tt1043726            4.2     50352
4       tt1060240            6.5        21
...           ...            ...       ...
73851   tt9805820            8.1        25
73852   tt9844256            7.5        24
73853   tt9851050            4.7        14
73854   tt9886934            7.0         5
73855   tt9894098            6.3       128

[73856 rows x 3 columns]

In [22]:
df_aka=pd.read_sql_query('''SELECT * FROM movie_akas''',con)
print(df_aka)

         movie_id  ordering                                    title region  \
0       tt0369610        10                            Джурасик свят     BG
1       tt0369610        11                        Jurashikku warudo     JP
2       tt0369610        12  Jurassic World: O Mundo dos Dinossauros     BR
3       tt0369610        13                  O Mundo dos Dinossauros     BR
4       tt0369610        14                           Jurassic World     FR
...           ...       ...                                      ...    ...
331698  tt9827784         2                       Sayonara kuchibiru   None
331699  tt9827784         3                            Farewell Song    XWW
331700  tt9880178         1                              La atención   None
331701  tt9880178         2                              La atención     ES
331702  tt9880178         3                            The Attention    XWW

       language        types   attributes  is_original_title
0            bg         None         None                0.0
1          None  imdbDisplay         None                0.0
2          None  imdbDisplay         None                0.0
3          None         None  short title                0.0
4          None  imdbDisplay         None                0.0
...         ...          ...          ...                ...
331698     None     original         None                1.0
331699       en  imdbDisplay         None                0.0
331700     None     original         None                1.0
331701     None         None         None                0.0
331702       en  imdbDisplay         None                0.0

[331703 rows x 8 columns]